repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: git@github.com-emu:melisource/fury_websec-git-hooks
    rev: v2.0.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]

  - repo: git@github.com-emu:melisource/fury_datasec-git-hooks.git
    rev: 1.2.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
        verbose: true
      - id: post_commit_hook
        stages: [post-commit]

  - repo: local
    hooks:
      - id: add-index
        name: Add index.php
        stages: [pre-commit]
        language: script
        entry: ./bin/add-index.sh