name: WooCommerce QIT Checks

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  pull-requests: write

jobs:
  run-qit-checks:
    runs-on: ubuntu-20.04
    env:
      NO_COLOR: 1
      QIT_DISABLE_ONBOARDING: yes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Composer dependencies
      run: composer install

    - name: Make Build
      run: make build

    - name: Install QIT via Composer
      run: composer require woocommerce/qit-cli

    - name: Add Partner
      run: ./vendor/bin/qit partner:add --user='${{ secrets.PARTNER_USER }}' --application_password='${{ secrets.PARTNER_SECRET }}'

    - name: Run QIT E2E tests
      run: ./vendor/bin/qit run:woo-e2e woocommerce-mercadopago --zip=woocommerce-mercadopago.zip --wait

    - name: Run PHPStan QIT checks
      run: ./vendor/bin/qit run:phpstan woocommerce-mercadopago --zip=woocommerce-mercadopago.zip --wait

    - name: Run PHP Compatibility checks
      run: ./vendor/bin/qit run:phpcompatibility woocommerce-mercadopago --zip=woocommerce-mercadopago.zip --wait

    - name: Run Security checks
      run: ./vendor/bin/qit run:security woocommerce-mercadopago --zip=woocommerce-mercadopago.zip --wait

    - name: Run Woo API tests
      run: ./vendor/bin/qit run:woo-api woocommerce-mercadopago --zip=woocommerce-mercadopago.zip --wait

    - uses: marocchino/sticky-pull-request-comment@v2
      if: failure()
      with:
        header: QIT Test Results
        recreate: true
        path: result.txt
